/**
 * Reference data for the Riichi Mahjong Reference tab.
 *
 * YAKU_REF — all scorable yaku with display info and riichi-ts key mappings.
 * TERMS    — glossary of common Riichi Mahjong terminology.
 */

export const YAKU_REF = [
  // ── 1-han ──────────────────────────────────────────────────────────────────
  {
    keys: ['riichi'],
    name: 'Riichi',
    closedHan: 1, openHan: null,
    isYakuman: false, isDoubleYakuman: false,
    description: 'Declare tenpai with a fully closed hand by paying 1000 points into the pot. Locks the hand — only the winning tile can be swapped in.',
  },
  {
    keys: ['menzentsumo'],
    name: 'Menzen Tsumo',
    closedHan: 1, openHan: null,
    isYakuman: false, isDoubleYakuman: false,
    description: 'Win by drawing your own winning tile (tsumo) with a fully closed hand.',
  },
  {
    keys: ['tanyao'],
    name: 'Tanyao',
    closedHan: 1, openHan: 1,
    isYakuman: false, isDoubleYakuman: false,
    description: 'All tiles in the hand are simples (2–8 in any suit). No terminals (1, 9) or honour tiles allowed.',
  },
  {
    keys: ['pinfu'],
    name: 'Pinfu',
    closedHan: 1, openHan: null,
    isYakuman: false, isDoubleYakuman: false,
    description: 'Four sequences, a non-scoring pair (not dragons or value winds), and a two-sided (ryanmen) wait. Scores 0 fu from sets.',
  },
  {
    keys: ['iipeikou'],
    name: 'Iipeiko',
    closedHan: 1, openHan: null,
    isYakuman: false, isDoubleYakuman: false,
    description: 'Two identical sequences (same tiles, same suit). Closed hand only.',
  },
  {
    keys: ['haku'],
    name: 'Haku',
    closedHan: 1, openHan: 1,
    isYakuman: false, isDoubleYakuman: false,
    description: 'A triplet (or quad) of Haku (白, white dragon) tiles.',
  },
  {
    keys: ['hatsu'],
    name: 'Hatsu',
    closedHan: 1, openHan: 1,
    isYakuman: false, isDoubleYakuman: false,
    description: 'A triplet (or quad) of Hatsu (發, green dragon) tiles.',
  },
  {
    keys: ['chun'],
    name: 'Chun',
    closedHan: 1, openHan: 1,
    isYakuman: false, isDoubleYakuman: false,
    description: 'A triplet (or quad) of Chun (中, red dragon) tiles.',
  },
  {
    keys: ['own wind east', 'own wind south', 'own wind west', 'own wind north'],
    name: 'Seat Wind',
    closedHan: 1, openHan: 1,
    isYakuman: false, isDoubleYakuman: false,
    description: 'A triplet (or quad) of the wind tile matching your current seat (East/South/West/North).',
  },
  {
    keys: ['round wind east', 'round wind south', 'round wind west', 'round wind north'],
    name: 'Round Wind',
    closedHan: 1, openHan: 1,
    isYakuman: false, isDoubleYakuman: false,
    description: 'A triplet (or quad) of the wind tile matching the current round wind (usually East or South).',
  },
  {
    keys: ['ippatsu'],
    name: 'Ippatsu',
    closedHan: 1, openHan: null,
    isYakuman: false, isDoubleYakuman: false,
    description: 'Win within one full round of discards after declaring riichi, before any other player calls a tile.',
  },
  {
    keys: ['haitei'],
    name: 'Haitei',
    closedHan: 1, openHan: 1,
    isYakuman: false, isDoubleYakuman: false,
    description: 'Win by drawing the very last tile from the wall (tsumo on the final draw).',
  },
  {
    keys: ['houtei'],
    name: 'Houtei',
    closedHan: 1, openHan: 1,
    isYakuman: false, isDoubleYakuman: false,
    description: 'Win by claiming the very last discard of the hand (ron on the final discard).',
  },
  {
    keys: ['rinshan'],
    name: 'Rinshan Kaihou',
    closedHan: 1, openHan: 1,
    isYakuman: false, isDoubleYakuman: false,
    description: 'Win on the supplemental tile drawn after declaring a kan.',
  },
  {
    keys: ['chankan'],
    name: 'Chankan',
    closedHan: 1, openHan: 1,
    isYakuman: false, isDoubleYakuman: false,
    description: 'Win by claiming a tile an opponent adds to an existing open pon to upgrade it to a kan.',
  },

  // ── 2-han ──────────────────────────────────────────────────────────────────
  {
    keys: ['daburu riichi'],
    name: 'Double Riichi',
    closedHan: 2, openHan: null,
    isYakuman: false, isDoubleYakuman: false,
    description: 'Declare riichi on your very first discard of the hand before any other player has discarded. Worth 2 han.',
  },
  {
    keys: ['chiitoitsu'],
    name: 'Chiitoitsu',
    closedHan: 2, openHan: null,
    isYakuman: false, isDoubleYakuman: false,
    description: 'Seven different pairs. Always scores 25 fu. All seven pairs must be different tiles.',
  },
  {
    keys: ['ittsu'],
    name: 'Ittsu',
    closedHan: 2, openHan: 1,
    isYakuman: false, isDoubleYakuman: false,
    description: 'Three sequences forming a complete 1–9 run in the same suit (e.g. 123m + 456m + 789m).',
  },
  {
    keys: ['sanshoku'],
    name: 'Sanshoku Doujun',
    closedHan: 2, openHan: 1,
    isYakuman: false, isDoubleYakuman: false,
    description: 'The same sequence (e.g. 456) in all three suits (Man, Pin, Sou) simultaneously.',
  },
  {
    keys: ['chanta'],
    name: 'Chanta',
    closedHan: 2, openHan: 1,
    isYakuman: false, isDoubleYakuman: false,
    description: 'Every set and the pair contains at least one terminal (1 or 9) or honour tile. Must have at least one sequence.',
  },
  {
    keys: ['toitoi'],
    name: 'Toitoi',
    closedHan: 2, openHan: 2,
    isYakuman: false, isDoubleYakuman: false,
    description: 'All four sets are triplets (or quads). No sequences. Can be achieved with open melds.',
  },
  {
    keys: ['sanankou'],
    name: 'San Ankou',
    closedHan: 2, openHan: 2,
    isYakuman: false, isDoubleYakuman: false,
    description: 'Three concealed triplets (formed without claiming discards). The fourth set may be open.',
  },
  {
    keys: ['sanshoku doukou'],
    name: 'Sanshoku Doukou',
    closedHan: 2, openHan: 2,
    isYakuman: false, isDoubleYakuman: false,
    description: 'The same triplet (e.g. three 5s) in all three suits (Man, Pin, Sou) simultaneously.',
  },
  {
    keys: ['sankantsu'],
    name: 'San Kantsu',
    closedHan: 2, openHan: 2,
    isYakuman: false, isDoubleYakuman: false,
    description: 'Three kans (quads) declared in a single hand. The fourth set may be a normal triplet or sequence.',
  },
  {
    keys: ['honroutou'],
    name: 'Honroutou',
    closedHan: 2, openHan: 2,
    isYakuman: false, isDoubleYakuman: false,
    description: 'All tiles are terminals (1, 9) or honour tiles. Always combined with Toitoi or Chiitoitsu.',
  },
  {
    keys: ['shosangen'],
    name: 'Shou Sangen',
    closedHan: 2, openHan: 2,
    isYakuman: false, isDoubleYakuman: false,
    description: 'Two dragon triplets plus a dragon pair. Always combined with the two individual dragon yaku.',
  },

  // ── 3-han ──────────────────────────────────────────────────────────────────
  {
    keys: ['honitsu'],
    name: 'Honitsu',
    closedHan: 3, openHan: 2,
    isYakuman: false, isDoubleYakuman: false,
    description: 'All tiles are from one suit (Man, Pin, or Sou) plus honour tiles. Honour-only tiles count toward this.',
  },
  {
    keys: ['junchan'],
    name: 'Junchan',
    closedHan: 3, openHan: 2,
    isYakuman: false, isDoubleYakuman: false,
    description: 'Every set and the pair contains a terminal (1 or 9). No honour tiles. Stricter version of Chanta.',
  },
  {
    keys: ['ryanpeikou'],
    name: 'Ryanpeiko',
    closedHan: 3, openHan: null,
    isYakuman: false, isDoubleYakuman: false,
    description: 'Two pairs of identical sequences (e.g. 123m 123m + 678p 678p). Closed only. Supersedes Iipeiko.',
  },

  // ── 6-han ──────────────────────────────────────────────────────────────────
  {
    keys: ['chinitsu'],
    name: 'Chinitsu',
    closedHan: 6, openHan: 5,
    isYakuman: false, isDoubleYakuman: false,
    description: 'All tiles are from a single suit (Man, Pin, or Sou). No honour tiles at all.',
  },

  // ── Yakuman ────────────────────────────────────────────────────────────────
  {
    keys: ['kokushimusou', 'kokushimusou 13 sides'],
    name: 'Kokushi Musou',
    closedHan: 0, openHan: null,
    isYakuman: true, isDoubleYakuman: false,
    description: 'One of each of the 13 terminals and honours (1m 9m 1p 9p 1s 9s + all 7 honours), plus one duplicate. Closed only. The 13-sided variant (waiting on any of the 13 tiles) scores double yakuman.',
  },
  {
    keys: ['suuankou', 'suuankou tanki'],
    name: 'Suu Ankou',
    closedHan: 0, openHan: null,
    isYakuman: true, isDoubleYakuman: false,
    description: 'Four fully concealed triplets. Closed only. The tanki (single-tile pair wait) variant scores double yakuman.',
  },
  {
    keys: ['daisangen'],
    name: 'Dai Sangen',
    closedHan: 0, openHan: 0,
    isYakuman: true, isDoubleYakuman: false,
    description: 'Triplets of all three dragons: Haku, Hatsu, and Chun. Can be open.',
  },
  {
    keys: ['shosuushi'],
    name: 'Shou Suushii',
    closedHan: 0, openHan: 0,
    isYakuman: true, isDoubleYakuman: false,
    description: 'Three wind triplets plus a pair of the fourth wind. Can be open.',
  },
  {
    keys: ['daisuushi'],
    name: 'Dai Suushii',
    closedHan: 0, openHan: 0,
    isYakuman: true, isDoubleYakuman: true,
    description: 'Triplets of all four wind tiles (East, South, West, North). Can be open. Scores double yakuman.',
  },
  {
    keys: ['tsuuiisou'],
    name: 'Tsuuiisou',
    closedHan: 0, openHan: 0,
    isYakuman: true, isDoubleYakuman: false,
    description: 'All tiles are honour tiles (winds and dragons only). No suited tiles. Can be open.',
  },
  {
    keys: ['chinroutou'],
    name: 'Chinroutou',
    closedHan: 0, openHan: 0,
    isYakuman: true, isDoubleYakuman: false,
    description: 'All tiles are terminals (1 and 9 in each suit only). No honour tiles. Can be open.',
  },
  {
    keys: ['ryuuiisou'],
    name: 'Ryuuiisou',
    closedHan: 0, openHan: 0,
    isYakuman: true, isDoubleYakuman: false,
    description: 'All tiles are "green" tiles: 2s 3s 4s 6s 8s and/or Hatsu. Can be open.',
  },
  {
    keys: ['chuurenpoto', 'chuurenpoto 9 sides'],
    name: 'Chuurenpoutou',
    closedHan: 0, openHan: null,
    isYakuman: true, isDoubleYakuman: false,
    description: 'The pure terminal hand: 1112345678999 in one suit plus any one tile. Closed only. The 9-sided variant (any of the 9 tiles completes it) scores double yakuman.',
  },
  {
    keys: ['suukantsu'],
    name: 'Suu Kantsu',
    closedHan: 0, openHan: 0,
    isYakuman: true, isDoubleYakuman: false,
    description: 'Four kans (quads) in a single hand. Can be open or closed.',
  },
  {
    keys: ['tenhou'],
    name: 'Tenhou',
    closedHan: 0, openHan: null,
    isYakuman: true, isDoubleYakuman: false,
    description: 'Dealer wins on their initial 13-tile deal (the starting 14th draw). Closed only. Extremely rare.',
  },
  {
    keys: ['chihou'],
    name: 'Chiihou',
    closedHan: 0, openHan: null,
    isYakuman: true, isDoubleYakuman: false,
    description: 'Non-dealer wins on their very first self-draw, before any claims have been made. Closed only.',
  },
]

export const TERMS = [
  { term: 'Agari', reading: 'アガリ', definition: 'Completing a winning hand. Announced when claiming ron or drawing tsumo.' },
  { term: 'Aka Dora', reading: '赤ドラ', definition: 'Red five tiles (0m, 0p, 0s). Each counts as one bonus dora regardless of the dora indicator.' },
  { term: 'Ankan', reading: '暗槓', definition: 'A closed kan formed entirely from tiles in your own hand. Does not open the hand; allows drawing a supplemental tile.' },
  { term: 'Bakaze', reading: '場風', definition: 'The round wind. Typically East (East round) or South (South round). A triplet of the bakaze tile scores Yakuhai.' },
  { term: 'Chankan', reading: '搶槓', definition: 'Stealing a tile an opponent adds to a pon to make a kan. The challenger wins by ron off that tile.' },
  { term: 'Chi', reading: 'チー', definition: 'Claiming the discard of the player to your left to form an open sequence. Limits the ability to declare riichi.' },
  { term: 'Chiitoitsu', reading: '七対子', definition: 'A special hand of seven different pairs. Always scores 25 fu, 2 han.' },
  { term: 'Chombo', reading: 'チョンボ', definition: 'A penalty for a rule violation (e.g. false win, incorrect hand). Usually costs the penalty equivalent of a dealer mangan payment.' },
  { term: 'Dora', reading: 'ドラ', definition: 'Bonus tiles worth +1 han each. The dora is one step above the indicator tile shown face-up beside the wall.' },
  { term: 'Fu', reading: '符', definition: 'Base points used to calculate hand value. Determined by hand composition (sets, pair, wait type) and win method. Rounded up to nearest 10.' },
  { term: 'Furo', reading: '副露', definition: 'Any open meld claimed from a discard: chi, pon, or open kan. Having furo prevents declaring riichi.' },
  { term: 'Haitei', reading: '海底', definition: 'The final tile drawn from the wall. Winning on haitei scores the Haitei yaku.' },
  { term: 'Han', reading: '飜', definition: 'The primary scoring unit. Each yaku contributes han; more han means more points. At 5+ han the score is capped at Mangan.' },
  { term: 'Honba', reading: '本場', definition: "Counter sticks placed on the table. Each honba adds 100 points per player (300 total for ron) to the hand's value." },
  { term: 'Honitsu', reading: '混一色', definition: 'A hand using only one number suit plus honour tiles. Scores 3 han closed, 2 open.' },
  { term: 'Houtei', reading: '河底', definition: 'The final discard of the hand. Winning by ron on houtei scores the Houtei yaku.' },
  { term: 'Ippatsu', reading: '一発', definition: 'A bonus yaku for winning within one full round of discards after declaring riichi.' },
  { term: 'Jikaze', reading: '自風', definition: 'Your seat wind. Changes each round (or when the dealer rotates). A triplet of your jikaze tile scores Yakuhai.' },
  { term: 'Kan', reading: '槓', definition: 'A set of four identical tiles. Declaring a kan allows drawing a supplemental tile and flipping an additional dora indicator.' },
  { term: 'Kanchan', reading: 'カンチャン', definition: 'A middle wait. Holding two tiles with a gap (e.g. 4-6) waiting for the middle tile (5). Scores 2 fu.' },
  { term: 'Kokushi', reading: '国士無双', definition: 'A yakuman hand requiring one of each of the 13 terminals and honours plus one duplicate.' },
  { term: 'Kuitan', reading: '喰い断', definition: 'Open Tanyao — allowed under EMA rules. Tanyao with open melds still scores 1 han.' },
  { term: 'Mangan', reading: '満貫', definition: 'The base score cap at 5 han (or 4 han 30+ fu / 3 han 70+ fu). Non-dealer ron: 8000 pts; dealer ron: 12000 pts.' },
  { term: 'Menzen', reading: '門前', definition: 'A fully closed hand with no open melds (ankan is allowed). Required for riichi, and some yaku are menzen-only.' },
  { term: 'Naki', reading: '鳴き', definition: 'Calling or claiming a tile — chi, pon, or kan. Interrupts the normal draw order.' },
  { term: 'Oya', reading: '親', definition: 'The dealer. The dealer has a 50% payment bonus on wins and losses compared to non-dealers.' },
  { term: 'Penchan', reading: 'ペンチャン', definition: 'An edge wait. Holding 1-2 waiting for 3, or 8-9 waiting for 7. Scores 2 fu.' },
  { term: 'Pinfu', reading: '平和', definition: 'A hand of four sequences, a non-value pair, and a two-sided (ryanmen) wait. Scores 0 fu from sets.' },
  { term: 'Pon', reading: 'ポン', definition: "Claiming any player's discard to form an open triplet. Opens the hand, preventing riichi." },
  { term: 'Renchan', reading: '連荘', definition: 'Dealer repeat. The dealer retains the deal if they win the hand or if the hand ends in a draw with the dealer in tenpai.' },
  { term: 'Riichi', reading: '立直', definition: 'Declaring tenpai with a closed hand by paying 1000 points. The hand is locked; only the winning tile completes it.' },
  { term: 'Rinshan', reading: '嶺上', definition: 'The supplemental tile drawn after declaring a kan. Winning on rinshan scores the Rinshan Kaihou yaku.' },
  { term: 'Ron', reading: 'ロン', definition: "Winning by claiming another player's discard as your winning tile. The discarder pays the full hand value." },
  { term: 'Ryanmen', reading: '両面', definition: 'A two-sided wait. Holding two consecutive tiles (e.g. 4-5) waiting for either end (3 or 6). Scores 0 fu.' },
  { term: 'Shanpon', reading: '双碰', definition: 'A dual-pair wait. Holding two pairs (e.g. 44 55) waiting to complete one as a triplet and keep the other as the pair.' },
  { term: 'Shanten', reading: '向聴', definition: 'The number of tiles you need to draw to reach tenpai. Tenpai = 0 shanten. A complete hand = -1 shanten.' },
  { term: 'Suji', reading: '筋', definition: 'Tile safety inference: if a player discarded a tile, tiles that form ryanmen sequences with it are less likely to be winning tiles.' },
  { term: 'Tanki', reading: '単騎', definition: 'A single-tile (pair) wait — waiting to complete the final pair. Scores 2 fu.' },
  { term: 'Tenpai', reading: '聴牌', definition: 'Ready to win. A hand that needs exactly one tile to complete. 0 shanten.' },
  { term: 'Tsumo', reading: 'ツモ', definition: 'Drawing your own winning tile from the wall. All other players pay a share of the hand value.' },
  { term: 'Uradora', reading: '裏ドラ', definition: 'Hidden dora tiles whose indicators are revealed only after a riichi win. Each matching tile adds 1 han.' },
  { term: 'Wareme', reading: '割れ目', definition: 'Optional rule: the player at the break point in the wall pays/receives double for that hand.' },
  { term: 'Yakuhai', reading: '役牌', definition: 'Value tiles: the three dragons (Haku, Hatsu, Chun) and wind tiles matching either seat wind or round wind. A triplet scores 1 han.' },
  { term: 'Yakuman', reading: '役満', definition: 'Maximum-value hands. Non-dealer: 32000 pts; dealer: 48000 pts. Some count as double yakuman (64000/96000 pts).' },
]
